name:                myawesomeserver
version:             0.0.1
synopsis:            It's a server!
description:         Example for usage of composite.
homepage:            https://github.com/ConferHealth/composite#readme
license:             BSD3
author:              Confer Health, Inc.
maintainer:          oss@confer.care
copyright:           2017 Confer Health, Inc.
category:            Records

default-extensions:
  - Arrows
  - ConstraintKinds
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 5
  - Frames
  - aeson
  - bytestring
  - classy-prelude
  - composite-aeson
  - composite-opaleye
  - configurator
  - fast-logger
  - lens
  - monad-logger
  - opaleye
  - postgresql-simple
  - product-profunctors
  - profunctors
  - resource-pool
  - servant
  - servant-server
  - vinyl
  - warp

ghc-options:
  - -Wall
  - -Werror

executables:
  myawesomeserver-exe:
    source-dirs:      app
    main:             Main.hs
    ghc-options:      -threaded -rtsopts -with-rtsopts=-N
    dependencies:     myawesomeserver

library:
  source-dirs:        src
