resolver: lts-14.3
packages:
  - composite-aeson
  - composite-aeson-refined
  - composite-base
  - composite-ekg
  - composite-opaleye
  - composite-swagger
  - example
flags: {}
extra-deps:
  - opaleye-0.6.7003.1
  - refined-0.2.3.0
  - transformers-0.5.5.2
nix:
  packages:
    - lzma
    - postgresql
    - zlib
