resolver: lts-12.17
packages:
  - composite-aeson
  - composite-aeson-refined
  - composite-base
  - composite-ekg
  - composite-opaleye
  - composite-swagger
  - example
flags: {}
extra-deps:
  - opaleye-0.6.7003.1
nix:
  packages:
    - lzma
    - postgresql
    - zlib
