resolver: lts-8.3
packages:
  - composite-aeson
  - composite-base
  - composite-ekg
  - composite-opaleye
  - example
extra-deps:
  - servant-0.10
  - servant-server-0.10
# nix:
#   enable: true
#   packages:
#     - postgresql
#     - zlib
flags: {}
extra-package-dbs: []
