resolver: nightly-2020-07-19
packages:
  - composite-aeson
  - composite-aeson-refined
  - composite-base
  - composite-ekg
  - composite-opaleye
  - composite-swagger
  - example
flags: {}
extra-deps:
  - vinyl-0.13.0
nix:
  packages:
    - lzma
    - postgresql
    - zlib
