name:                composite-opaleye
version:             0.2.0.0
synopsis:            Opaleye SQL for Frames records
description:         Integration between Frames records and Opaleye SQL, allowing records to be stored, retrieved, and queried from PostgreSQL.
homepage:            https://github.com/ConferHealth/composite#readme
license:             BSD3
author:              Confer Health, Inc.
maintainer:          oss@confer.care
copyright:           2017 Confer Health, Inc.
category:            Records

dependencies:
  - base >= 4.7 && < 5
  - basic-prelude
  - bytestring
  - composite-base
  - lens
  - opaleye
  - postgresql-simple
  - product-profunctors
  - profunctors
  - template-haskell
  - text
  - vinyl

default-extensions:
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - PolyKinds
  - ScopedTypeVariables
  - StrictData
  - TemplateHaskell
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options: -Wall -O2

library:
  source-dirs: src
